version: '2'
services:
  nginx:
    container_name : nginx
    image: nginx:1.11.8
    depends_on:
     - ckan
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./nginx/odp.conf:/etc/nginx/conf.d/default.conf
  ckan:
    container_name : ckan
    build: ./ckan/
    entrypoint: /docker-entrypoint.sh
    ports:
     - "8080:8080"
    volumes:
     - ./data/ckan_storage:/var/lib/ckan
    depends_on:
     - solr
    environment:
       POSTGRES_HOST: "${POSTGRES_HOST}"
       POSTGRES_PORT: "${POSTGRES_PORT}"
       POSTGRES_USER: "${POSTGRES_USER}"
       POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
       POSTGRES_DATASTORE_USER: "${POSTGRES_DATASTORE_USER}"
       POSTGRES_DATASTORE_PASSWORD: "${POSTGRES_DATASTORE_PASSWORD}"
       PGPASSWORD: "${POSTGRES_PASSWORD}"
       POSTGRES_CKAN_DBNAME: "${POSTGRES_CKAN_DBNAME}"
       POSTGRES_CKAN_DATASTORE_DBNAME: "${POSTGRES_CKAN_DATASTORE_DBNAME}"
       CKAN_SQLALCHEMY_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_CKAN_DBNAME}"
       CKAN_DATASTORE_WRITE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_CKAN_DATASTORE_DBNAME}"
       CKAN_DATASTORE_READ_URL: "postgresql://${POSTGRES_DATASTORE_USER}:${POSTGRES_DATASTORE_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_CKAN_DATASTORE_DBNAME}"
       CKAN_SITE_URL: "${CKAN_SITE_URL}"
       CKAN_SITE_ID: "default"
       CKAN_STORAGE_PATH: "/var/lib/ckan"
       CKAN_DATAPUSHER_URL: "http://datapusher:8800"
       CKAN_SOLR_URL: "http://solr:8983/solr/${POSTGRES_CKAN_DBNAME}"
       CKANEXT__CLOUDSTORAGE__DRIVER: "${CLOUDSTORAGE_DRIVER}"
       CKANEXT__CLOUDSTORAGE__CONTAINER_NAME: "${CLOUDSTORAGE_NAME}"
       CKANEXT__CLOUDSTORAGE__DRIVER_OPTIONS: "${CLOUDSTORAGE_OPTIONS}"
       SOLR_URL: "http://solr:8983/solr/${POSTGRES_CKAN_DBNAME}"
       EMAIL_TO: "${EMAIL_TO}"
       ERROR_EMAIL_FROM: "${ERROR_EMAIL_FROM}"
       CKAN_SMTP_SERVER: "${CKAN_SMTP_SERVER}"
       CKAN_SMTP_STARTTLS: "${CKAN_SMTP_STARTTLS}"
       CKAN_SMTP_USER: "${CKAN_SMTP_USER}"
       CKAN_SMTP_PASSWORD: "${CKAN_SMTP_PASSWORD}"
       CKAN_SMTP_MAIL_FROM: "${CKAN_SMTP_MAIL_FROM}"
  datapusher:
    container_name: ckan_datapusher
    build: ./datapusher/
    ports:
     - "8800:8800"
    depends_on:
     - ckan
    environment:
      SERVER_NAME: "${CKAN_SITE_URL}"
  solr:
    container_name : solr
    image: ckan/solr:dev-v2.6
    ports:
     - "8983:8983"
